add daily cronjob to clean out job management
geopython/demo.pygeoapi.io pull request #46
Opened 2023-12-04 18:00 UTC by tomkralidis

As a result of https://github.com/geopython/demo.pygeoapi.io/commit/49a426bb223264b290a1b28041c581b49a54c547 for GISE pgeoapi workshop preparation, adding cronjob to remove job management data on a daily basis.

Note: I have not done this for `services/pygeoapi_master/Dockerfile.alpine`, so any help would be appreciated for the alpine image (are we using it?  If not, should we delete it?).

2023-12-04 19:01 UTC, doublebyte1 approved these changes

2023-12-05 14:35 UTC, justb4 requested changes
See my proposed changes in Dockerfile and cronfile.

`Dockerfile.alpine` is not used, we can even remove, as Alpine base images for Dockerfiles are not necessary anymore with slim Debian/Ubuntu base images.

2023-12-05 14:35 UTC, justb4 commented on services/pygeoapi_master/Dockerfile
> +
IMO lines 11-19 can be made much simpler, only one line: 

`COPY ./demo.pygeoapi.io.cron /etc/cron.d/demo.pygeoapi.io.cron`.

*  `/etc/cron.d` is in container already, with jobs
* `crontab` program/command is not required when already copying to `/etc/cron.d/`
* file permissions are preserved in GH, no need for `chmod`

2023-12-05 14:35 UTC, justb4 commented on services/pygeoapi_master/demo.pygeoapi.io.cron
> +0 1 * * * /bin/rm -f /tmp/pygeoapi-process-manager.db > /proc/1/fd/1 2>/proc/1/fd/2
can be simpler: `/bin/rm -f /tmp/pygeoapi-process-manager.db > /dev/null 2>&1`

2023-12-08 02:55 UTC, tomkralidis commented on services/pygeoapi_master/demo.pygeoapi.io.cron
> +0 1 * * * /bin/rm -f /tmp/pygeoapi-process-manager.db > /proc/1/fd/1 2>/proc/1/fd/2
Fixed.

2023-12-08 02:56 UTC, tomkralidis commented
Thanks @justb4.  Updates pushed, for review.

2023-12-08 13:00 UTC, justb4 approved these changes
Proof will be in the pudding, on demo server can check:

* `docker exec -it pygeoapi_master ls -l /etc/cron.d`
* `docker exec -it pygeoapi_master ls -l --time=birth /tmp/pygeoapi-process-manager.db`

2023-12-08 13:01 UTC, merged

2023-12-08 13:04 UTC, justb4 commented
I can check as this Docker image is only rebuilt/deployed when the pygeoapi image is renewed, we still need GH Workflows, see issue #36.

2023-12-11 12:09 UTC, justb4 commented
Hmm, I think we/I overlooked that `cron` is not available within Ubuntu on Docker. I think even if we install `cron` in the Dockerfile, the jobs (`cron` daemon) won't run. Remember how in the first versions of GeoHealthCheck we had a special utility/Docker base for this? 

There are many references how to do this, but quite involved as a Docker container is supposed to run a single process. I also worked on several solutions. One is using [supervisor](https://gdevillele.github.io/engine/admin/using_supervisord/) for example an `AWStats` Docker Image with scheduled stats generation and serving these with Apache: https://github.com/justb4/docker-awstats . In a conf one can specify processes to run:
https://github.com/justb4/docker-awstats/blob/master/confs/supervisord.conf
Maybe there are other solutions these days for cron in Docker, or for scheduled jobs. 

Using the demo base OS cron with a `docker exec pygeoapi_master rm -f ...` is another possibility, but IMO not very clean.